kentcdodds/cross-env

- package.json
- src/index.js
- src/index.test.js
Checks if the platform is windows. If it is, adds the process.env.APPDATA var to the options sent into ```spawn```.
Also opted for ```cross-spawn-async``` as it is the core of cross-spawn, and the other package is only for added spawnSync support, which is not used here.
> fix(env): checks if windows platform, then send in APPDATA env var.

- package.json
- src/index.js
- src/index.test.js
When you use ``cross-env`` you will lose any original env variable, which includes not being able to 
* run ``DEBUG=* npm run a-script-using-cross-env``
* use ``process.env.npm_package_config_MY_CONFIG`` instead a npm script using cross-env
Those use cases are quite common, so I suggest with this PR that ``cross-env`` does not **initialize** a whole new env, but **merges** with existing one.
> Merge with original environment instead of defining a new one

- src/index.js
- src/index.test.js
This fixes #6. I also added handling of quoted strings. Since `split` in the tests doesn't work correctly when a quoted strings contains equality signs, I made the expected environment explicit (mostly because the "correct" regex has quite some logic in it).
Happy :christmas_tree: :smiley:
> fix(lib): Handle special characters and quoted strings

- src/index.js
- src/index.test.js
Exit codes are swallowed at the moment. So if I run tests and they fail, I still get `0` exit code.
Here is the problem:
Fixed behaviour:
My test file:
```js
'use strict';
process.on('uncaughtException', err => {
console.error(err);
console.log(err.stack);
process.exit(1);
});
throw new Error('OMG!');
```
> fix(spawn): Propagate spawned process exit code

- package.json
- src/index.test.js
when running npm test on windows, a "PATH" variable was added to the environment while in windows the path variable is "Path".
This caused two path variables in the env object in the tests, which caused the expected and actual results to diverge.
Since the use of `getPathVar` was removed from the lib in previous commits, I thought it ok to remove it's use in the test cases.
> fix broken tests in windows

- src/index.js
- src/index.test.js
I'm using cross-env with [concurrently](https://github.com/kimmobrunfeldt/concurrently). There is a option to kill other processes when one of them exit. But the process using cross-env never exit, because the SIGTERM is not propagated to the child process. This PR fix this issue.
> feat(kill): Propagate SIGTERM to created process

- package.json
- src/command.js
- src/command.test.js
- src/index.js
- src/index.test.js
- Converts environment vars used in `npm run` to account for windows/linux respectively
- Add tests for command
- Update `npm test` to look for all .test.js files
Essentially it makes `cross-env PORT=3000 $npm_package_main` work, otherwise on Windows you get `Error: Cannot find module 'C:\Repo\$npm_package_main'` since Windows expects env variables to be in the format of `%npm_package_main%`
As a side note, the `linebreak-style` rule makes it a frustrating experience committing against the repo as it fails all commits despite the fact that Git converts `CRLF` to `LF` automatically on commit (this is a default setting for Git on Windows)
> feat(vars): Convert environment vars

- src/index.js
- src/index.test.js
- Adds the 4 main kill signals that NodeJS handles
- Add tests for kill signals, update test description
I couldn't get a loop over the event names to work for some reason, so ended up just hard coding them all
Satisfies #31 for my uses
> fix(kill): Add all kill signals

- package.json
If someone wants to require('cross-env') let it be es5
> package.json: "main": "dist/index.js"

- README.md
- package.json
Since the cross-env can only support Node.js version 4.0 or greater as of [cross-env version 3.0.0](https://github.com/kentcdodds/cross-env/releases/tag/v3.0.0), I added an `engines` attribute to `package.json` which will enforce the presence of Node.js version 4.0 or greater. If someone tries to run/build cross-env with an older version of Node.js, the `engines` attribute will cause an error to be thrown as soon as they try to run `npm install` (or otherwise try to run/build the project).
In addition, I also added a **`Prerequisites`** section to `README.md` which states that Node.js version 4.0 or greater is required.
> Enforce minimum Node.js version requirement using 'engines' attribute package.json

- README.md
I think it's worth acknowledging that Bash on Windows doesn't have this problem. :) I've used `cross-env` many times in the past (love it!) but a big benefit of BoW is better *nix compat.
> Update README to mention Bash on Windows

- README.md
Unsure how you want to organize this info, hope this works for you.
Key thing: `cross-var` must come before `cross-env`.
> docs(README): Add doc for cross-var.

- CHANGELOG.md
Need to go up 2 directories to get out of `/blob/`, as currently the link will try sending you to `https://github.com/kentcdodds/cross-env/blob/releases` - which doesn't exist.
> fix: update path to release page

- src/bin/cross-env.js
> fix(bin): babelify bin

- src/command.js
- src/command.test.js
Hello [again](https://github.com/kentcdodds/cross-env/pull/85). :)
Now for the actual contribution I mentioned in #85. It turns out it supersedes #85, but I submitted #85 anyway because I thought it could still be useful for you to make a patch release, and you did, so that's great! This contribution however, is a breaking change.
If you feed cross-env on Windows with something like `echo $npm_package_name $npm_package_version`, it correctly runs `echo %npm_package_name% %npm_package_version%`. But if instead you feed it with `echo $npm_package_name/$npm_package_version` (notice the slash in the middle), then it runs `echo %npm_package_name%`. That is because the command argument is replaced by the converted *first* match of a variable pattern. The goal of this PR is to make cross-env …
> feat(args): convert embedded and braced variables in command args

- README.md
- package.json
- src/index.js
- src/index.test.js
Like #77 but using Node.js 4.8's shell option.
No tests because the behavior change only happens inside of `spawn`. There is no perceived difference when using the mock.
> Support quoted scripts

- src/command.js
- src/command.test.js
Before, Windows-style env variables (`%test%`) would be converted to UNIX-style format (`$test`) in UNIX
systems. That was an undocumented feature. I've removed that to simplify code a bit. Of course, UNIX
to Windows format still works, as that's the intended use of cross-env.
BREAKING CHANGE: `%windows_style%` env variables will no longer be converted to `$unix_style` in UNIX
machines. To fix it, use always the UNIX syntax, cross-env will change the format in Windows
machines as needed
As discussed in https://github.com/kentcdodds/cross-env/issues/90#issuecomment-286800030
> fix: Remove Windows => UNIX variable conversion

- src/index.js
- src/variable.js
- src/variable.test.js
Since this was the only blocker for releasing the next major version, I decided to give it a try.
Before:
`cross-env FOO=$NODE_ENV echo $FOO`
Output (before this PR): `"$NODE_ENV"` on UNIX, `"%NODE_ENV%"` on Windows.
Output (after this PR): `"development"` (or whatever value NODE_ENV has)
I've added some logic in the part of the parser that processes the right-hand side of variable assignments (in this example, the `$NODE_ENV` in the `FOO=$NODE_ENV` expression). It will find all occurences of UNIX-style env variables and replace them with their value.
I've also had to change the program logic a little bit so `commandConvert` only operates on the real command and its arguments, not on the variable assignments.
Fixes #90
> fix: Resolve value of env variables before invoking cross-spawn

- README.md
- src/bin/cross-env-shell.js
- src/index.js
- src/index.test.js
Revert the default bin (cross-env) to its v3 behavior (not using the shell option). Add a new
(cross-env-shell)  which uses the shell option.
BREAKING CHANGE: Scripts using quotes or escape sequences will see a difference in behavior.
Switching to the second bin should resolve any issue.
Closes #99.
See prior discussion in #99 et and #102.
> feat(bin): two bins (shell, non-shell)

- README.md
- src/variable.test.js
Added two tests that show the use the same JSON string on Windows and UNIX, despite not being totally sure that's how it's done. Would it be better to test against JSON.parse?
Also added a real example to the README.
I had to use the **--no-verify** flag, as **prettier-eslint** is messing up the **triple backslash** in the **tests**. What can I do to prevent that?
And just noticed that **travis** build is also **failing** precisely because of the triple backslash (**lint script**), despite the tests themselves running just fine.
Closes #30
> JSON string tests and example

- src/index.test.js
When tests are run, node logs warnings - `MaxListenersExceededWarning: Possible EventEmitter memory
leak detected`. This fixes  thewarning by setting the max listeners to 20 on `process`(`EventEmitter`)
When running tests, the following warnings are logged:
```
(node:10188) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit
(node:10188) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:10188) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGBREAK listeners added. Use emitter.setMaxListeners() to increase limit
(node:10188) MaxListenersExceededWarning: Possible …
```
> test: Fix EventEmitter.MaxListenersExceededWarning warning

- src/command.js
- src/command.test.js
- src/index.js
- src/index.test.js
Command arguments can have URLs which should not be normalized. This adds optional parameter   to function `commandConvert`(default `false`) and normalizes **only the command**, and not the command arguments.
This also adds tests for cmd normalization on windows
- index.test.js
- should normalize command on windows
- should not normalize command arguments on windows
- command.test.js - normalizes command on windows
Issue reported by @weizhenye - https://github.com/kentcdodds/cross-env/pull/130#issuecomment-319887970
Edit: Turns out there was an issue reported for this as well.
Closes #133
> fix: Normalize command only and not command args(windows)

- src/index.js
If a function reference is passed directly to `Array#map`, it is invoked with the array item,
index, and the array. Instead of passing the function reference, this invokes it explicitly with just the
array item. See
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-fn-reference-in-iterator.md
> fix: Do not pass function reference to `Array#map`

- jest.config.js
- src/__tests__/command.js
- src/command.js
- src/index.js
Fixes https://github.com/kentcdodds/cross-env/issues/145, check it for more context.
**What**: Remove env variables that don't exist from the converted commands in Windows.
**Why**: In Windows, if a `%variable%` is not defined (or it's the empty string), the shell won't parse it, and instead it will interpret it as the literal `%variable%` string. In UNIX, an undefined or empty variable wuld be interpreted as an empty string.
**How**:  The entire `process.env` map that would be passed down to the child process is now also passed to the `commandConvert` function. While converting a env variable to the Windows format (`$var => %var%`), it's checked if it actually has any value, and if it isn't, it's ommitted entirely.
**Checklist**:
> Remove env variables that don't exist from the converted commands in Windows.

- src/__tests__/index.js
- src/index.js
**What**: fix #148 
**Why**: cross-env-shell does not work for macOS
**How**: The best possible way by @brucejo75
ALL credit goes to @brucejo75 i just making the PR because cross-env-shell does not work cross platform :)
> Handle escaping and single quotes

- src/__tests__/index.js
- src/index.js
see #167 
Not really sure what you want the solution to be.  Apparently you want cross-env to use backlash as an esapce character even though Windows itself does not do this. So, this patch lets esaped backslashes through so if you want to pass `\\someshare\somefolder` you'd have to pass `\\\\someshare\\somefolder` as the argument.
also i tried running `npm run add-contributor` but appearently it doesn't work at the moment
**What**:  allow backslashes through
**Why**:  beacuse otherwise you can't pass backslash through and can not specify UNC paths
**How**:  adjust the regular expression related to backslashes
**Checklist**:
```
C:\Users\gregg\src\cross-env>npm run add-contributor
> cross-env@0.0.0-semantically-released add-contributor C:\Users\gregg\src\cross-env
> kcd-scripts …
```
> Allow backslash

- package.json
Like it says on the tin. 
The main reason I'm doing this is to help us suppress some warnings that we end up seeing when doing a webpack build of the main process for an electron app: 
https://github.com/nteract/nteract/issues/1707#issuecomment-396803564
> Upgrade cross-spawn

- README.md
The PR lists [@naholyr/cross-env](https://www.npmjs.com/package/@naholyr/cross-env), a `cross-env` fork that supports setting default values, as requested [here](https://github.com/kentcdodds/cross-env/pull/157#issuecomment-367304017).
There is a second fork implementing the same feature, but with non-standard syntax:
https://www.npmjs.com/package/cross-env-default
ref #157, #170
> docs(README): list @naholyr/cross-env in Other Solutions section

- README.md
- package.json
**What**: Bumped dependency `cross-spawn` to `^7.0.0`
**Why**: cross-spawn 7.0.0 removed 2 dependencies but also removed compatibily with node.js 7 and lower.
**How**: Just changed the package.json
**Checklist**:
Added a warning in README.md, should also update the badge but I don't know how.
This is a breaking change since it removes compatibility with node.js 7 and lower, so it requires a new major version.
> bumped cross-spawn to version 7.0.0

- README.md
**What**:
Update README.md to give warning on node.js version requirements to users installing latest version of cross-env.
**Why**:
The documentation is currently warning about the node.js version requirements of the previous major release.
**How**:
Edited README.md
**Checklist**:
- [-] Tests
> Update warning about Node versions

- src/__tests__/index.js
- src/index.js
**What**:
Signals should delegate to the child process to determine what to
do as cross-env is a facade to spawning them cross platform.
SIGINT, in particular, can decide swallow the signal and continue on.
cross-env needs to wait for the child to decide when it's time to exit.
fixed leaking `process.on` listeners.
**Why**:
See https:github.com/jtlapp/node-cleanup
> When you hit Ctrl-C, you send a SIGINT signal to each process in the
> current process group. A process group is set of processes that are
> all supposed to end together as a group instead of persisting
> independently. However, some programs, such as Emacs, intercept and
> repurpose SIGINT so that it does not end the process. In such cases,
> SIGINT should not end any processes of the group.
The current implementation …
> fix: signal handling

- README.md
Addresses documentation request in #62
**What**: Add example showing how to set more than one env var at a time
**Why**: Gap in documentation 
**How**: Editing the README
**Checklist**:
> Add multi vars example to README
